version: '2'

services:
  owlh-master:
    build:
      context: ./master/
    hostname: owlh-master
    restart: always
    ports:
      - "50001:50001"
      - "80:80"
      - "443:443"
        
  owlh-node:
    build:
      context: ./node/
    hostname: owlh-node
    restart: always
    depends_on:
      - owlh-master
    ports:
        - "50002:50002"
    links:
      - owlh-master
